# language: ruby
# before_install:
# - gem install bundler
# rvm:
# - 1.9.3
# before_script:
# - psql -c 'create database pbp_test;' -U postgres
# script:
# - RAILS_ENV=test bundle exec rake db:migrate --trace
# - bundle exec rake db:test:prepare
# - bundle exec rake
# env:
#   global:
#     secure: dySkedt3UsGY/k1Gf4773871T3Twe+jyaFlFPOjvSO51k1bpqvy9koHSSa/emOawTgeTtIzSNC6nOkiHsqwXS2iJeL6GmKC4S3wbPYx3E8i7huXd573AjouNSrliqPl3KRYLNTTwn6lB6RFv36WRs0s+6goKCM0uEHB60Cyt9Vc=
# deploy:
#   provider: heroku
#   api_key:
#     secure: k31DgQiIuw2qp676DjeSO9bzP0PgdEFiuo4mHdTecMzlFBKUFbniabsHyu0UxM9br8zb2tHkdOke7fnEmsf5xc/srCoGG6tu15uaZbL060C873juE57UwzzHGNg2oBRQtADz0IAhDgyxQqoFuWBtE2ANaEVm8fe6rbUuLldZbZA=
#   app: desolate-oasis-7380
#   on:
#     branch: master
#     rvm: 1.9.3
#     repo: zachgersh/pbp
#   run: rake db:migrate

deploy:
  provider: heroku
  app: Rails_With_Auth # optional if it's the same as your repo name
  api_key: k31DgQiIuw2qp676DjeSO9bzP0PgdEFiuo4mHdTecMzlFBKUFbniabsHyu0UxM9br8zb2tHkdOke7fnEmsf5xc/srCoGG6tu15uaZbL060C873juE57UwzzHGNg2oBRQtADz0IAhDgyxQqoFuWBtE2ANaEVm8fe6rbUuLldZbZA=